local utils = require("utils")
local op = require("plenary.operators")
describe("tuple_cmp", function()
    it("computes less-than properly", function()
    assert.truthy(utils.tuple_less({1,2,3}, {1,2,4}))
    assert.falsy(utils.tuple_less({1,2,3}, {1,2,3}))
    assert.falsy(utils.tuple_less({1,5,3}, {1,2,4}))
    assert.falsy(utils.tuple_less({2,0,0}, {1,2,4}))
end)
end)
