local tutils = require("units.tests.test_utils")
local ts_utils = require("nvim-treesitter.ts_utils")
local utils = require("utils")
local units = require("units")
local Query = require("units.query")
describe("creates test node", function()
	it("appends unit test with go filetype", function()
		tutils.open_test_file("foo.go")
		utils.vim_motion("3j")
		units.add_test_function("TestAddNumbers")
		utils.vim_motion("G")
		local test_fn_node = Query.get_closest_function()
		assert.truthy(test_fn_node, vim.api.nvim_buf_get_lines(0, 0, -1, false))
		assert.same("TestAddNumbers", Query.get_function_name(test_fn_node))
	end)

	it("appends unit test with python filetype", function()
		tutils.open_test_file("foo.py")
		utils.vim_motion("3j")
		units.add_test_function("test_add_numbers")
		utils.vim_motion("jjjj")
		local test_fn_node = Query.get_closest_function()
		assert.truthy(test_fn_node, vim.api.nvim_buf_get_lines(0, 0, -1, false))
		assert.same("test_add_numbers", Query.get_function_name(test_fn_node))
	end)
end)
